#!/usr/bin/env bash

# checar si eres root
if [[ 0 != $( id -u ) ]]; then
    echo 'El script debe correrse con super poderes (root).'
    exit 1
fi

# resetear firewalld
systemctl restart firewalld.service 

# remover gemas
gem uninstall --force -ax rack tilt rack-protection sinatra eventmachine daemons thin 

# borrar app
rm myapp.rb

# remover ruby y rubygems
echo 'si quieres remover ruby y rubygems, ejecuta: 

    dnf -y remove ruby rubygems'
