#!/usr/bin/env bash

# checar si eres root
if [[ 0 != $( id -u ) ]]; then
    echo 'El script debe correrse con super poderes (root).'
    exit 1
fi

# resetear firewalld
systemctl restart firewalld.service

# agregar usuario para haproxy con accesado desde la red de richard
echo 'provee el password de root de mysql'
mysql -u root -p -e "drop user 'haproxy'@'192.168.1.%'; drop user 'haproxy'@'localhost';"
